### ISSUE TITLE
Apple Native Payment returning Cancelled by the user

### ISSUE THREAD

**Issue by nicowernli** [jonasbark/flutter_stripe_payment#102]
This is the code of the app I'm running:

```dart
import 'package:flutter/material.dart';
import 'package:stripe_payment/stripe_payment.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        textTheme: TextTheme(
          button: TextStyle(color: Colors.white),
        ),
      ),
      home: MyHomePage(title: 'Testing Native Payment'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);
  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  void initState() {
    StripePayment.setOptions(StripeOptions(
      publishableKey: 'PUBLISHABLE_KEY',
      merchantId: 'MERCHANT_ID',
      androidPayMode: 'test',
    ));
    super.initState();
  }

  void _nativePayment() async {
    await StripePayment.paymentRequestWithNativePay(
      androidPayOptions: AndroidPayPaymentRequest(
        line_items: [
          LineItem(
            total_price: "1.20",
            quantity: "1",
            unit_price: "1.20",
            currency_code: "USD",
          ),
        ],
      ),
      applePayOptions: ApplePayPaymentOptions(
        countryCode: "US",
        currencyCode: "USD",
        items: [
          ApplePayItem(
            label: "Service",
            amount: "1.20",
          ),
        ],
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text(widget.title)),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            FlatButton(
              onPressed: _nativePayment,
              color: Theme.of(context).accentColor,
              textColor: Theme.of(context).textTheme.button.color,
              child: Text('Native Payment'),
            ),
          ],
        ),
      ),
    );
  }
}
```

Running `stripe_payment: ^1.0.5`

The error when clicking the button is the following:

```bash
[VERBOSE-2:ui_dart_state.cc(148)] Unhandled Exception: PlatformException(cancelled, Cancelled by user, null)
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
#1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:316:33)
<asynchronous suspension>
#2      StripePayment._paymentRequestWithApplePay (package:stripe_payment/src/stripe_payment.dart:67:34)
<asynchronous suspension>
#3      StripePayment.paymentRequestWithNativePay (package:stripe_payment/src/stripe_payment.dart:56:14)
#4      _MyHomePageState._nativePayment (package:flutter_app/main.dart:42:25)
<asynchronous suspension>
#5      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:654:14)
#6      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:729:32)
#7      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
#8      TapGestureRecognizer._checkUp (package:flutter/sr<…>
```

**Comment by macmatrix** [comment]
This works for me

```
Future<void> createPaymentMethodNative() async {

    List<ApplePayItem> items = [];

    items.add(ApplePayItem(
      label: 'Order nr xxx',
      amount: '10.00',
    ));

    items.add(ApplePayItem(
      label: 'xxx',
      amount: '10.00',
    ));

    PaymentMethod paymentMethod = PaymentMethod();

    Token token = await StripePayment.paymentRequestWithNativePay(
      androidPayOptions: AndroidPayPaymentRequest(
        total_price: '10.00',
        currency_code: 'GBP',
      ),
      applePayOptions: ApplePayPaymentOptions(
        countryCode: 'GB',
        currencyCode: 'GBP',
        items: items,
      ),
    );

    paymentMethod = await StripePayment.createPaymentMethod(
      PaymentMethodRequest(
        card: CreditCard(
          token: token.tokenId,
        ),
      ),
    );

    paymentMethod != null
        ? // process payment
        : showDialog(
            context: context,
            builder: (BuildContext context) => ShowDialogToDismiss(
                title: 'Error',
                content:
                    'It is not possible to pay with this card. Please try again with a different card',
                buttonText: 'CLOSE'));
  }
```

**Comment by nicowernli** [comment]
Hey @macmatrix is there any way to test this on simulator? Maybe that's the problem. I'm testing on iPhone 11 simulator running iOS 13.0.

**Comment by nicowernli** [comment]
This is xcode log when running it in a real device

```bash
2019-12-02 15:17:01.677599+0100 Runner[58919:2103516] flutter: Observatory listening on http://127.0.0.1:51083/ljCVanBQ-eE=/
2019-12-02 15:17:09.407956+0100 Runner[58919:2102078] [General] Connection to remote alert view service failed
2019-12-02 15:17:10.415591+0100 Runner[58919:2103503] [VERBOSE-2:ui_dart_state.cc(148)] Unhandled Exception: PlatformException(cancelled, Cancelled by user, null)
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
#1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:316:33)
<asynchronous suspension>
#2      StripePayment._paymentRequestWithApplePay (package:stripe_payment/src/stripe_payment.dart:67:34)
<asynchronous suspension>
#3      StripePayment.paymentRequestWithNativePay (package:stripe_payment/src/stripe_payment.dart:56:14)
#4      _MyHomePageState.createPaymentMethodNative (package:flutter_app/main.dart:54:39)
<asynchronous suspension>
#5      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:654:14)
#6      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:729:32)
#7      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
#8      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:365:11)
#9      TapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:275:7)
#10     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:455:9)
#11     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:75:13)
#12     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:102:11)
#13     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:218:19)
#14     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
#15     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
#16     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
#17     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
#18     _rootRunUnary (dart:async/zone.dart:1136:13)
#19     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#20     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#21     _invoke1 (dart:ui/hooks.dart:263:10)
#22     _dispatchPointerDataPacket (dart:ui/hooks.dart:172:5)
```

**Comment by macmatrix** [comment]
@nicowernli where do you want me to test it? I am not clear on what you ask. I suggest to test native pay on a real device rather than a simulator

**Comment by nicowernli** [comment]
Yes, I tested on real device and I also have the same problem, even when I use your code. Still trying to figure out whats going on

**Comment by macmatrix** [comment]
have you set up Apple Pay in Xcode, sign the app and also added a merchant in Xcode?

**Comment by nicowernli** [comment]
Yes all setup still having the same problem.

<img width="695" alt="Captura de pantalla 2019-12-02 a las 17 12 43" src="https://user-images.githubusercontent.com/2279893/70041064-c7e61100-15bc-11ea-84d5-badb8f74edbb.png">

**Comment by nicowernli** [comment]
After updating macOS, Xcode, cocoapods, etc I can open the native Apple Pay. I don't know if it is related or not, but it works for me now.

**Comment by macmatrix** [comment]
@nicowernli this is a great news! Can you confirm if this is working for your code above OR if this means you can successfully pay with Apple Pay using `setStripeAccount`? Also is there another way where we can chat about this issue? I am fine to use github but equally happy to use other tool, ie discord?

**Comment by nicowernli** [comment]
I'm able to open Apple Pay and to get the token of a Card and converting that token into a Paymentmethod. Didn't finish the operation because I'm having a different problem, but the app itself looks like it's working 100% even using `setStripeAccount(null)`.

Give me 1 hour or so and I'll let you know if I can complete and order or not.

**Comment by macmatrix** [comment]
ok, fine. I am worried that updating macOS Xcode etc will make my app to crash but if you succeed then it is worth trying it. I am looking forward to hearing from you

**Comment by nicowernli** [comment]
OK.... I stopped the app, relaunch it again and now is crashing again... I have to keep testing this

**Comment by Marcusg62** [comment]
> After updating macOS, Xcode, cocoapods, etc I can open the native Apple Pay. I don't know if it is related or not, but it works for me now.

I have the same issue. macOS, Xcode and cocoapods is up to date but I still have this issue. What else did you do that could have solved it?

**Comment by Marcusg62** [comment]
> > After updating macOS, Xcode, cocoapods, etc I can open the native Apple Pay. I don't know if it is related or not, but it works for me now.
> 
> I have the same issue. macOS, Xcode and cocoapods is up to date but I still have this issue. What else did you do that could have solved it?

Ok I solved. Silly mistake - did not specify merchantID in the setOptions function. 

> > After updating macOS, Xcode, cocoapods, etc I can open the native Apple Pay. I don't know if it is related or not, but it works for me now.
> 
> I have the same issue. macOS, Xcode and cocoapods is up to date but I still have this issue. What else did you do that could have solved it?

The problem was not specifying merchant id in the setOptions function.

**Comment by macmatrix** [comment]
@Marcusg62 did you manage to make it work `setStripeAccount(null)` with `nativePay` in iOS?

**Comment by nicowernli** [comment]
This still happens to me. I believe that the Apple Pay doesn't work nicely with the `CustomScrollView` or something similar. So the problem comes when the plugin tries to open the Apple Pay when the page is scrolled down.

**Comment by Marcusg62** [comment]
I did not use null and yes, got it working. Sorry for delayed response.

**Comment by macmatrix** [comment]
@Marcusg62 can you please summarise your workflow and the key commands you give in the client and in the server?

**Comment by nicowernli** [comment]
I found out that I was creating the message when trying to rebuild the widget while opening the Apple Pay screen. I'm going to close now.
