### ISSUE TITLE
Build failed with an exception - on both 0.1.0 and 0.2.0

### ISSUE THREAD

**Issue by naseebbajracharya** [jonasbark/flutter_stripe_payment#156]
I tried installing the package and ever since I install the package and integrate it, the application won't start and shows the following errors on the console.

e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\stripe_payment-0.1.0\android\src\main\java\de\jonasbark\stripepayment\StripeDialog.kt: (41, 15): Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type Dialog?

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':stripe_payment:compileDebugKotlin'.
> Compilation error. See log for more details

**Comment by jonasbark** [comment]
Why are you using such an old version?

**Comment by naseebbajracharya** [comment]
cause the newer version also throws numerous errors at startup

**Comment by alikamal1** [comment]
@naseebbajracharya you can open the file 
`C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\stripe_payment-0.1.0\android\src\main\java\de\jonasbark\stripepayment`
and edit the line 41 to include `?` at the fuction call of dialog like this
```
dialog?.setTitle(title)
```

**Comment by naseebbajracharya** [comment]
@alikamal1 
I tried and it does not throw any error but the application crashes at the starting point with the message "Unfortunately application has stopped working"

**Comment by alikamal1** [comment]
use `flutter clean`

**Comment by naseebbajracharya** [comment]
@alikamal1 no changes at all even after using flutter clean.
shows the same problem  "application has stopped working"

**Comment by alikamal1** [comment]
@naseebbajracharya You may have another issue not related to package, try remove the package and run debug again

**Comment by naseebbajracharya** [comment]
@alikamal1 
yeah, removing stripe_payment works perfectly!
but whenever I include the package, the app won't work at all!!

**Comment by alikamal1** [comment]
@naseebbajracharya not sure what wrong without any logs of the error, try flutter clean again and remove `.gradle` folder which you can find inside android folder then make sure you include the package without `^` like this `stripe_payment: 0.1.0` run flutter pub get and run the debug again, if the issue remain you can either upgrade to the latest version or use another package like this one https://pub.dev/packages/flutter_stripe_payment

**Comment by naseebbajracharya** [comment]
@alikamal1 none of those methods worked.

This is my code based on 0.1.0 & 0.2.0

  Widget _cardsTab(){
    return StoreConnector<AppState, AppState>(
          
          converter: (store) => store.state,
          
          builder: (_, state){
            _addCard(cardToken) async {
              final User user = state.user;
              //update current user's data to include card token
              await http.put('http://10.0.2.2:1337/users/${user.id}', body: {
                "card_token": cardToken
              },
              headers: {
                "Authorization": "Bearer ${user.jwt}"
              });

              http.Response response = await http.post('http://10.0.2.2:1337/card/add', body: {
                "source": cardToken, 
                "customer": user.customerId
              });

              final responseData = json.decode(response.body);
              return responseData;
            }
            return Column(children: <Widget>[
              Padding(padding: EdgeInsets.only(top: 5.0)),
              RaisedButton(
                elevation: 8.0,
                child: Text('Add Payment Card Details'),

                onPressed: () async {

                  final String cardToken = await StripeSource.addSource();
                  final card = await _addCard(cardToken);

                  //action to add card to display
                  StoreProvider.of<AppState>(context).dispatch(AddCardAction(card));

                  //action to update card token
                  StoreProvider.of<AppState>(context).dispatch(UpdateCardTokenAction(card['id']));
                  //snackbar
                  final snackbar = SnackBar(
                    content: Text('Your Payment Card Has Been Added!', style: TextStyle(color: Colors.green))
                    );
                    _scaffoldKey.currentState.showSnackBar(snackbar);
                }),
              Expanded(child: ListView(
                children: state.cards.map<Widget>((c) => (ListTile(
                  leading: CircleAvatar(
                    backgroundColor: Colors.redAccent,
                    child: Icon(
                      Icons.credit_card,
                      color: Colors.white,
                    ),
                  ),
                  title: Text("${c['card']['exp_month']}/${c['card']['exp_year']}, ${c['card']['last4']}"),
                  subtitle: Text(c['card']['brand']),
                  trailing: FlatButton(
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.all(Radius.circular(10.0))
                    ),
                    child: Text('Set As Primary', style: TextStyle(fontWeight: FontWeight.bold, color: Colors.green)),
                    onPressed: () => print('pressed'),
                  )
                ))).toList(),
              ))
            ]);
          });
  }

**Comment by alikamal1** [comment]
@naseebbajracharya could you show the error log that's would be helpful to debug the issue you had

**Comment by naseebbajracharya** [comment]
![Screenshot (5043)](https://user-images.githubusercontent.com/34349150/83334359-bb214c00-a2c5-11ea-89e5-4171357c5d4b.png)

This is all I get, also to mention those 9 problems indicated are all related to the body, headings of different dart pages!

**Comment by naseebbajracharya** [comment]
@alikamal1 This is all I get, also to mention those 9 problems indicated are all related to the body, headings of different dart pages!
![Screenshot (5043)](https://user-images.githubusercontent.com/34349150/83334442-4d295480-a2c6-11ea-8a84-de607d877a5e.png)

**Comment by alikamal1** [comment]
@naseebbajracharya I meant the log file in your project directory `flutter_01.log` see if it's generated when crash happened, if not please update to latest package version and share the errors you have and maybe @jonasbark could help you as well

**Comment by naseebbajracharya** [comment]
@alikamal1 I can't find it in my directory!
I can simply upgrade to the latest version but the example looks so confusing to me. The older ones had a simple method to use that with 
```
onPressed: () {
              print("Ready: ${StripeSource.ready}");
              StripeSource.addSource().then((String token) {
                _addSource(token);
              });
            }
```

**Comment by alikamal1** [comment]
@naseebbajracharya you can use it as following
```dart
onPressed: () {
print("Ready: ${StripeSource.ready}");
StripePayment.paymentRequestWithCardForm(CardFormPaymentRequest()).then((paymentMethod) {
      _addSource(paymentMethod.id);
});
}
```

**Comment by naseebbajracharya** [comment]
@alikamal1 with latest version 1.0.7

Launching lib\main.dart on Android SDK built for x86 in debug mode...
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
D8: Cannot fit requested classes in a single dex file (# methods: 73537 > 65536)
com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives:
The number of method references in a .dex file cannot exceed 64K.
Learn how to resolve this issue at https://developer.android.com/tools/building/multidex.html
	at com.android.builder.dexing.D8DexArchiveMerger.getExceptionToRethrow(D8DexArchiveMerger.java:131)
	at com.android.builder.dexing.D8DexArchiveMerger.mergeDexArchives(D8DexArchiveMerger.java:118)
	at com.android.build.gradle.internal.transforms.DexMergerTransformCallable.call(DexMergerTransformCallable.java:102)
	at com.android.build.gradle.internal.tasks.DexMergingTaskRunnable.run(DexMergingTask.kt:444)
	at com.android.build.gradle.internal.tasks.Workers$ActionFacade.run(Workers.kt:335)
	at org.gradle.workers.internal.AdapterWorkAction.execute(AdapterWorkAction.java:50)
	at org.gradle.workers.internal.DefaultWorkerServer.execute(DefaultWorkerServer.java:47)
	at org.gradle.workers.internal.NoIsolationWorkerFactory$1$1$1.create(NoIsolationWorkerFactory.java:65)
	at org.gradle.workers.internal.NoIsolationWorkerFactory$1$1$1.create(NoIsolationWorkerFactory.java:61)
	at org.gradle.internal.classloader.ClassLoaderUtils.executeInClassloader(ClassLoaderUtils.java:98)
	at org.gradle.workers.internal.NoIsolationWorkerFactory$1$1.execute(NoIsolationWorkerFactory.java:61)
	at org.gradle.workers.internal.AbstractWorker$1.call(AbstractWorker.java:44)
	at org.gradle.workers.internal.AbstractWorker$1.call(AbstractWorker.java:41)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:416)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:406)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:102)
	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.call(DelegatingBuildOperationExecutor.java:36)
	at org.gradle.workers.internal.AbstractWorker.executeWrappedInBuildOperation(AbstractWorker.java:41)
	at org.gradle.workers.internal.NoIsolationWorkerFactory$1.execute(NoIsolationWorkerFactory.java:56)
	at org.gradle.workers.internal.DefaultWorkerExecutor$3.call(DefaultWorkerExecutor.java:215)
	at org.gradle.workers.internal.DefaultWorkerExecutor$3.call(DefaultWorkerExecutor.java:210)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.runExecution(DefaultConditionalExecutionQueue.java:215)
	at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.runBatch(DefaultConditionalExecutionQueue.java:164)
	at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.run(DefaultConditionalExecutionQueue.java:131)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.android.tools.r8.CompilationFailedException: Compilation failed to complete
	at com.android.tools.r8.utils.t.a(:55)
	at com.android.tools.r8.D8.run(:11)
	at com.android.builder.dexing.D8DexArchiveMerger.mergeDexArchives(D8DexArchiveMerger.java:116)
	... 34 more
Caused by: com.android.tools.r8.utils.AbortException: Error: null, Cannot fit requested classes in a single dex file (# methods: 73537 > 65536)
	at com.android.tools.r8.utils.Reporter.a(:21)
	at com.android.tools.r8.utils.Reporter.a(:7)
	at com.android.tools.r8.dex.VirtualFile.a(:33)
	at com.android.tools.r8.dex.VirtualFile$h.a(:5)
	at com.android.tools.r8.dex.ApplicationWriter.a(:13)
	at com.android.tools.r8.dex.ApplicationWriter.write(:35)
	at com.android.tools.r8.D8.d(:44)
	at com.android.tools.r8.D8.b(:1)
	at com.android.tools.r8.utils.t.a(:23)
	... 36 more


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeDexDebug'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: 
     The number of method references in a .dex file cannot exceed 64K.
     Learn how to resolve this issue at https://developer.android.com/tools/building/multidex.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 4m 26s
[!] The shrinker may have failed to optimize the Java bytecode.
    To disable the shrinker, pass the `--no-shrink` flag to this command.
    To learn more, see: https://developer.android.com/studio/build/shrink-code
Exception: Gradle task assembleDebug failed with exit code 1
Exited (sigterm)

**Comment by alikamal1** [comment]
@naseebbajracharya I think this related to AndroidX make sure you follow the instruction  at https://pub.dev/packages/stripe_payment#android if you did and still have the issue take a look at https://stackoverflow.com/questions/36785014/the-number-of-method-references-in-a-dex-file-cannot-exceed-64k-api-17

**Comment by naseebbajracharya** [comment]
@alikamal1 those issues are solved!
now all I get is this error with the latest one after trying to save the payment card

Exception has occurred.
_CastError (type 'PaymentMethod' is not a subtype of type 'String' in type cast)

**Comment by alikamal1** [comment]
@naseebbajracharya that's because you are trying to cast `PaymentMethod` as `String` which is a class not a string, you can access its values as you need them like `PaymentMethod.id`
![image](https://user-images.githubusercontent.com/19997775/83562862-f076a580-a522-11ea-9634-c23db92e70b7.png)
