### ISSUE TITLE
Error Running Example

### ISSUE THREAD

**Issue by zuwuko** [jonasbark/flutter_stripe_payment#159]
I downloaded the example, ran it and it errors immediately:

`[ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: MissingPluginException(No implementation found for method setOptions on channel stripe_payment)
E/flutter (10980): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:154:7)
E/flutter (10980): <asynchronous suspension>
E/flutter (10980): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:329:12)
E/flutter (10980): #2      StripePayment.setOptions (package:stripe_payment/src/stripe_payment.dart:22:14)
E/flutter (10980): #3      _MyAppState.initState (package:stripe_payment_example/main.dart:38:19)
E/flutter (10980): #4      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4644:58)
E/flutter (10980): #5      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4480:5)
E/flutter (10980): #6      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3450:14)
E/flutter (10980): #7      Element.updateChild (package:flutter/src/widgets/framework.dart:3218:18)
E/flutter (10980): #8      RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:1132:16)
E/flutter (10980): #9      RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:1103:5)
E/flutter (10980): #10     RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:1045:17)
E/flutter (10980): #11     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2607:19)
E/flutter (10980): #12     RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:1044:13)
E/flutter (10980): #13     WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:925:7)
E/flutter (10980): #14     WidgetsBinding.scheduleAttachRootWidget.<anonymous closure> (package:flutter/src/widgets/binding.dart:906:7)
E/flutter (10980): #15     _rootRun (dart:async/zone.dart:1180:38)
E/flutter (10980): #16     _CustomZone.run (dart:async/zone.dart:1077:19)
E/flutter (10980): #17     _CustomZone.runGuarded (dart:async/zone.dart:979:7)
E/flutter (10980): #18     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1019:23)
E/flutter (10980): #19     _rootRun (dart:async/zone.dart:1184:13)
E/flutter (10980): #20     _CustomZone.run (dart:async/zone.dart:1077:19)
E/flutter (10980): #21     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:1003:23)
E/flutter (10980): #22     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:23:15)
E/flutter (10980): #23     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398:19)
E/flutter (10980): #24     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429:5)
E/flutter (10980): #25     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
E/flutter (10980): 
`

**Comment by kttailor** [comment]
I am facing same issue. Did you find any solution?

**Comment by ziphawkteamusa** [comment]
I having the same issue. Was able to run the example successfully using `flutter run`.  But on pressing `Create payment method with card` button on the UI, I get snackbar saying 

```
MissingPluginException: no implementation found for method createPaymentMethod on channel stripe_payment.
```
I thought it was because I did not do `flutter pub upgrade stripe_payment` from within `example` folder, but that does not resolve the problem. Instead I am getting a new error

```
> flutter pub upgrade stripe_payment
Error on line 1, column 1 of https://pub.dartlang.org/api/packages/%2F%2Fstripe_payment: "name" field doesn't match expected name "//stripe_payment".
Running "flutter pub upgrade" in ....
pub upgrade failed (65; Error on line 1, column 1 of https://pub.dartlang.org/api/packages/%2F%2Fstripe_payment: "name" field doesn't match expected name
"//stripe_payment".)
```

Also deleted `.pub-cache`, continue to receive the same error.

Running dart 2.8.1, flutter 1.17.0. Here is `flutter doctor` output

```
[✓] Flutter (Channel stable, v1.17.0, on Mac OS X 10.15.4 19E287, locale en-US)
    • Flutter version 1.17.0 at /Users/rishabh/development/flutter
    • Framework revision e6b34c2b5c (5 weeks ago), 2020-05-02 11:39:18 -0700
    • Engine revision 540786dd51
    • Dart version 2.8.1


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/rishabh/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/rishabh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.9.1

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[!] IntelliJ IDEA Community Edition (version 2019.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[!] IntelliJ IDEA Community Edition (version 2019.3.2)
    • IntelliJ at /Applications/ /IntelliJ IDEA CE.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] VS Code (version 1.45.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[✓] Connected device (1 available)
    • Pixel 3a • 99LAY1ANP6 • android-arm64 • Android 10 (API 29)
```

**Comment by ziphawkteamusa** [comment]
> I having the same issue. Was able to install and run the example on Android (Pixel 3a) successfully using `flutter run`. But on pressing `Create payment method with card` button on the UI, I get snackbar saying
> 
> ```
> MissingPluginException: no implementation found for method createPaymentMethod on channel stripe_payment.
> ```
> 
> I thought it was because I did not do `flutter pub upgrade stripe_payment` from within `example` folder, but that does not resolve the problem.
> 
> Also deleted `.pub-cache`, continue to receive the same error.
> 
> Running dart 2.8.1, flutter 1.17.0. Here is `flutter doctor` output
> 
> ```
> [✓] Flutter (Channel stable, v1.17.0, on Mac OS X 10.15.4 19E287, locale en-US)
>     • Flutter version 1.17.0 at /Users/rishabh/development/flutter
>     • Framework revision e6b34c2b5c (5 weeks ago), 2020-05-02 11:39:18 -0700
>     • Engine revision 540786dd51
>     • Dart version 2.8.1
> 
> 
> [✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
>     • Android SDK at /Users/rishabh/Library/Android/sdk
>     • Platform android-29, build-tools 29.0.2
>     • ANDROID_HOME = /Users/rishabh/Library/Android/sdk
>     • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
>     • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
>     • All Android licenses accepted.
> 
> [✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
>     • Xcode at /Applications/Xcode.app/Contents/Developer
>     • Xcode 11.4.1, Build version 11E503a
>     • CocoaPods version 1.9.1
> 
> [✓] Android Studio (version 3.6)
>     • Android Studio at /Applications/Android Studio.app/Contents
>     • Flutter plugin version 45.1.1
>     • Dart plugin version 192.7761
>     • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
> 
> [!] IntelliJ IDEA Community Edition (version 2019.3.2)
>     • IntelliJ at /Applications/IntelliJ IDEA CE.app
>     ✗ Flutter plugin not installed; this adds Flutter specific functionality.
>     ✗ Dart plugin not installed; this adds Dart specific functionality.
>     • For information about installing plugins, see
>       https://flutter.dev/intellij-setup/#installing-the-plugins
> 
> [!] IntelliJ IDEA Community Edition (version 2019.3.2)
>     • IntelliJ at /Applications/ /IntelliJ IDEA CE.app
>     ✗ Flutter plugin not installed; this adds Flutter specific functionality.
>     ✗ Dart plugin not installed; this adds Dart specific functionality.
>     • For information about installing plugins, see
>       https://flutter.dev/intellij-setup/#installing-the-plugins
> 
> [✓] VS Code (version 1.45.1)
>     • VS Code at /Applications/Visual Studio Code.app/Contents
>     • Flutter extension version 3.11.0
> 
> [✓] Connected device (1 available)
>     • Pixel 3a • 99LAY1ANP6 • android-arm64 • Android 10 (API 29)
> ```

So I was able to resolve the issue. Did two thing - used publishable key from my own stripe account. And made change recommended by @andreabtis  in #8

**Comment by grsomani** [comment]
Facing similar issue! Anyone any updates on this?
I tried the every other comment on this thread. Yet same issue.

**Comment by RizzWann** [comment]
e: [C:\flutter\.pub-cache\hosted\pub.dartlang.org\stripe_android-2.4.0\android\src\main\kotlin\com\flutter\stripe\StripeAubecsDebitPlatformViewFactory.kt](): (13, 1): Class 'StripeAubecsDebitPlatformViewFactory' is not abstract and does not implement abstract base class member public abstract fun create(p0: Context?, p1: Int, p2: Any?): PlatformView defined in io.flutter.plugin.platform.PlatformViewFactory
e: [C:\flutter\.pub-cache\hosted\pub.dartlang.org\stripe_android-2.4.0\android\src\main\kotlin\com\flutter\stripe\StripeAubecsDebitPlatformViewFactory.kt](): (19, 5): 'create' overrides nothing
e: [C:\flutter\.pub-cache\hosted\pub.dartlang.org\stripe_android-2.4.0\android\src\main\kotlin\com\flutter\stripe\StripeSdkCardFormPlatformViewFactory.kt](): (13, 1): Class 'StripeSdkCardFormPlatformViewFactory' is not abstract and does not implement abstract base class member public abstract fun create(p0: Context?, p1: Int, p2: Any?): PlatformView defined in io.flutter.plugin.platform.PlatformViewFactory


ANY FIX
