### ISSUE TITLE
No such method error in Android but works in iOS

### ISSUE THREAD

**Issue by aWildRiceHasAppeared** [jonasbark/flutter_stripe_payment#204]
Hey all

I have been trying to work on Card Payment in Android (Physical device) but have been facing this issue. 
I have followed the setup for Android where:

    android.useAndroidX=true
    android.enableJetifier=true

but still to no avail. 
The method works perfectly on iOS devices though, only on my android device (physical; Moto G8) that it constantly crashes my app whenever I hit the submit button.

The below is the error output I've got. Would love to know where to correct my mistake.

[ERROR:flutter/shell/platform/android/platform_view_android_jni_impl.cc(44)] java.lang.NoSuchMethodError: No virtual method brand(Ljava/lang/String;)Lcom/stripe/android/model/Card$Builder; in class Lcom/stripe/android/model/Card$Builder; or its super classes (declaration of 'com.stripe.android.model.Card$Builder' appears in /data/app/com.the_foodilicious_app-13f7xvJn759Tt-VM3Hg1Bg==/base.apk!classes3.dex)
E/flutter (10336): 	at com.gettipsi.stripe.util.Converters.createCard(Converters.java:199)
E/flutter (10336): 	at com.gettipsi.stripe.StripeModule.createTokenWithCard(StripeModule.java:157)
E/flutter (10336): 	at de.jonasbark.stripepayment.StripePaymentPlugin.onMethodCall(StripePaymentPlugin.kt:33)
E/flutter (10336): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/flutter (10336): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/flutter (10336): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:692)
E/flutter (10336): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/flutter (10336): 	at android.os.MessageQueue.next(MessageQueue.java:334)
E/flutter (10336): 	at android.os.Looper.loop(Looper.java:174)
E/flutter (10336): 	at android.app.ActivityThread.main(ActivityThread.java:6929)
E/flutter (10336): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter (10336): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/flutter (10336): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:870)
E/flutter (10336): 
F/flutter (10336): [FATAL:flutter/shell/platform/android/platform_view_android_jni_impl.cc(943)] Check failed: CheckException(env). 
F/libc    (10336): Fatal signal 6 (SIGABRT), code -6 (SI_TKILL) in tid 10336 (oodilicious_app), pid 10336 (oodilicious_app)
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'motorola/lima_32/lima:9/PMDS29.70-70-2/ac5451:user/release-keys'
Revision: 'PVT'
ABI: 'arm'
pid: 10336, tid: 10336, name: oodilicious_app  >>> com.the_foodilicious_app <<<
signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
Abort message: '[FATAL:flutter/shell/platform/android/platform_view_android_jni_impl.cc(943)] Check failed: CheckException(env). 
'
    r0  00000000  r1  00002860  r2  00000006  r3  00000008
    r4  00002860  r5  00002860  r6  bec9812c  r7  0000010c
    r8  bec98174  r9  bec98288  r10 aa39881c  r11 0000002c
    ip  bec980c8  sp  bec98118  lr  ac830e49  pc  ac828c96
backtrace:
    #00 pc 0001cc96  /system/lib/libc.so (abort+58)
    #01 pc 01019883  /data/app/com.the_foodilicious_app-13f7xvJn759Tt-VM3Hg1Bg==/lib/arm/libflutter.so (offset 0x1007000)
    #02 pc 000000e7  <unknown>

**Comment by Gintasz** [comment]
I'm also experiencing a similar problem. Did you find a solution?

```
PaymentMethod stripePaymentMethod = await StripePayment.createPaymentMethod(
      PaymentMethodRequest(
        card: CreditCard(
          number: card.cardNumber,
          name: card.cardHolderName,
          cvc: card.cvv,
          expMonth: card.expiryMonth,
          expYear: card.expiryYear2Digits
        )
      )
    );
```
```
E/AndroidRuntime(10938): FATAL EXCEPTION: DefaultDispatcher-worker-1
E/AndroidRuntime(10938): Process: mobappkurimas.ekoshine, PID: 10938
E/AndroidRuntime(10938): java.lang.NoSuchFieldError: No instance field type of type Ljava/lang/String; in class Lcom/stripe/android/model/PaymentMethod; or its superclasses (declaration of 'com.stripe.android.model.PaymentMethod' appears in /data/app/mobappkurimas.ekoshine-1/base.apk:classes3.dex)
E/AndroidRuntime(10938): 	at com.gettipsi.stripe.util.Converters.convertPaymentMethodToWritableMap(Converters.java:291)
E/AndroidRuntime(10938): 	at com.gettipsi.stripe.StripeModule$9.onSuccess(StripeModule.java:385)
E/AndroidRuntime(10938): 	at com.gettipsi.stripe.StripeModule$9.onSuccess(StripeModule.java:376)
E/AndroidRuntime(10938): 	at com.stripe.android.ApiOperation.dispatchResult(ApiOperation.kt:40)
E/AndroidRuntime(10938): 	at com.stripe.android.ApiOperation.access$dispatchResult(ApiOperation.kt:14)
E/AndroidRuntime(10938): 	at com.stripe.android.ApiOperation$execute$1$1.invokeSuspend(ApiOperation.kt:33)
E/AndroidRuntime(10938): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
E/AndroidRuntime(10938): 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
E/AndroidRuntime(10938): 	at android.os.Handler.handleCallback(Handler.java:739)
E/AndroidRuntime(10938): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime(10938): 	at android.os.Looper.loop(Looper.java:158)
E/AndroidRuntime(10938): 	at android.app.ActivityThread.main(ActivityThread.java:7230)
E/AndroidRuntime(10938): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(10938): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
E/AndroidRuntime(10938): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```

This also doesn't work (same crash)

```
PaymentMethod stripePaymentMethod = await StripePayment.paymentRequestWithCardForm(CardFormPaymentRequest(requiredBillingAddressFields: "name"));
```

**Comment by Gintasz** [comment]
I added
```
useProguard false
shrinkResources false
```

to build.gradle and it seems ok for me
