### ISSUE TITLE
Crash on android device when launch

### ISSUE THREAD

**Issue by jayrparro** [jonasbark/flutter_stripe_payment#229]
Hi,

I'm using v1.0.9, but it always crashing when running on android device/emulator.

gradle.properties config is also set -

```
android.useAndroidX=true
android.enableJetifier=true
```

Error log:
```
E/AndroidRuntime(11419): java.lang.VerifyError: Rejecting class de.jonasbark.stripepayment.StripePaymentPlugin because it failed compile-time verification (declaration of 'de.jonasbark.stripepayment.StripePaymentPlugin' appears in /data/app/com.abc.base.apk:classes7.dex)
E/AndroidRuntime(11419): 	at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(GeneratedPluginRegistrant.java:34)
E/AndroidRuntime(11419): 	at com.abc.MainActivity.configureFlutterEngine(MainActivity.kt:15)
E/AndroidRuntime(11419): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onAttach(FlutterActivityAndFragmentDelegate.java:179)
E/AndroidRuntime(11419): 	at io.flutter.embedding.android.FlutterActivity.onCreate(FlutterActivity.java:410)
E/AndroidRuntime(11419): 	at android.app.Activity.performCreate(Activity.java:6904)
E/AndroidRuntime(11419): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1136)
E/AndroidRuntime(11419): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3266)
E/AndroidRuntime(11419): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3415)
E/AndroidRuntime(11419): 	at android.app.ActivityThread.access$1100(ActivityThread.java:229)
E/AndroidRuntime(11419): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1821)
E/AndroidRuntime(11419): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(11419): 	at android.os.Looper.loop(Looper.java:148)
E/AndroidRuntime(11419): 	at android.app.ActivityThread.main(ActivityThread.java:7325)
E/AndroidRuntime(11419): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(11419): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
E/AndroidRuntime(11419): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```

Anyone have also encountered this issue and possible fix?
Thanks.

**Comment by victorevox** [comment]
Hi, same issue here:

```
/flutter ( 7852): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: PlatformException(error, Attempt to invoke virtual method 'android.content.Context android.content.Context.getApplicationContext()' on a null object reference, null, java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Context android.content.Context.getApplicationContext()' on a null object reference
E/flutter ( 7852): 	at com.stripe.android.Stripe.<init>(Stripe.java:89)
E/flutter ( 7852): 	at com.gettipsi.stripe.StripeModule.init(StripeModule.java:97)
E/flutter ( 7852): 	at de.jonasbark.stripepayment.StripePaymentPlugin.onMethodCall(StripePaymentPlugin.kt:16)
E/flutter ( 7852): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/flutter ( 7852): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/flutter ( 7852): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:692)
E/flutter ( 7852): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/flutter ( 7852): 	at android.os.MessageQueue.next(MessageQueue.java:336)
E/flutter ( 7852): 	at android.os.Looper.loop(Looper.java:174)
E/flutter ( 7852): 	at android.app.ActivityThread.main(ActivityThread.java:7356)
E/flutter ( 7852): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter ( 7852): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/flutter ( 7852): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
E/flutter ( 7852): )
E/flutter ( 7852): #0      StandardMethodCodec.decodeEnvelope
package:flutter/…/services/message_codecs.dart:582
E/flutter ( 7852): #1      MethodChannel._invokeMethod
package:flutter/…/services/platform_channel.dart:159
E/flutter ( 7852): <asynchronous suspension>
E/flutter ( 7852): #2      MethodChannel.invokeMethod
package:flutter
```

Maybe this plugin needs to support new embeding APIs [https://flutter.dev/docs/development/packages-and-plugins/plugin-api-migration](link)
