### ISSUE TITLE
Unsupported platform view macos

### ISSUE THREAD

**Issue by Amean** [jonasbark/flutter_stripe_payment#306]
Is flutter_stripe able to run on macOS? The readme mentions specifically only android and iOS but the example app includes a macOS folder

Describe the Bug:

The flutter_stripe example works with iOS. However, when I run the flutter-stripe example on macOS and navigate to either the card payment using web hooks screen, card payment without web hooks screen, setup future payment screen, or card themes screen I get an 
Unsupported operation: Unsupported platform view error that shows up in the UI as well as this corresponding error message in the terminal:

══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY
╞═══════════════════════════════════════════════════════════
The following UnsupportedError was thrown building
_MethodChannelCardField(dirty, dependencies:
[_LocalizationsScope-[GlobalKey#3ef09], _InheritedTheme],
state:
_MethodChannelCardFieldState#a41b4):
Unsupported operation: Unsupported platform view

The relevant error-causing widget was:
  _MethodChannelCardField
  _MethodChannelCardField:file:///Users/camin/development/fl
  utter/.pub-cache/hosted/pub.dartlang.org/flutter_stripe-1.
  0.2/lib/src/widgets/card_field.dart:108:18

When the exception was thrown, this was the stack:
#0      _MethodChannelCardFieldState.build
(package:flutter_stripe/src/widgets/card_field.dart:280:7)
#1      StatefulElement.build
(package:flutter/src/widgets/framework.dart:4775:27)
#2      ComponentElement.performRebuild
(package:flutter/src/widgets/framework.dart:4658:15)
#3      StatefulElement.performRebuild
(package:flutter/src/widgets/framework.dart:4831:11)
#4      Element.rebuild
(package:flutter/src/widgets/framework.dart:4348:5)
#5      ComponentElement._firstBuild
(package:flutter/src/widgets/framework.dart:4636:5)
#6      StatefulElement._firstBuild
(package:flutter/src/widgets/framework.dart:4822:11)
#7      ComponentElement.mount
(package:flutter/src/widgets/framework.dart:4631:5)
...     Normal element mounting (7 frames)
#14     Element.inflateWidget
(package:flutter/src/widgets/framework.dart:3666:14)
#15     Element.updateChild
(package:flutter/src/widgets/framework.dart:3418:18)
#16     _DecorationElement._mountChild
(package:flutter/src/material/input_decorator.dart:1591:31)
#17     _DecorationElement.mount
(package:flutter/src/material/input_decorator.dart:1604:5)
...     Normal element mounting (20 frames)
#37     Element.inflateWidget
(package:flutter/src/widgets/framework.dart:3666:14)
#38     MultiChildRenderObjectElement.inflateWidget
(package:flutter/src/widgets/framework.dart:6324:36)
#39     MultiChildRenderObjectElement.mount
(package:flutter/src/widgets/framework.dart:6335:32)
...     Normal element mounting (19 frames)
#58     Element.inflateWidget
(package:flutter/src/widgets/framework.dart:3666:14)
#59     MultiChildRenderObjectElement.inflateWidget
(package:flutter/src/widgets/framework.dart:6324:36)
#60     MultiChildRenderObjectElement.mount
(package:flutter/src/widgets/framework.dart:6335:32)
...     Normal element mounting (241 frames)
#301    Element.inflateWidget
(package:flutter/src/widgets/framework.dart:3666:14)
#302    MultiChildRenderObjectElement.inflateWidget
(package:flutter/src/widgets/framework.dart:6324:36)
#303    Element.updateChild
(package:flutter/src/widgets/framework.dart:3418:18)
#304    RenderObjectElement.updateChildren
(package:flutter/src/widgets/framework.dart:5749:32)
#305    MultiChildRenderObjectElement.update
(package:flutter/src/widgets/framework.dart:6347:17)
#306    Element.updateChild
(package:flutter/src/widgets/framework.dart:3405:15)
#307    ComponentElement.performRebuild
(package:flutter/src/widgets/framework.dart:4683:16)
#308    StatefulElement.performRebuild
(package:flutter/src/widgets/framework.dart:4831:11)
#309    Element.rebuild
(package:flutter/src/widgets/framework.dart:4348:5)
#310    StatefulElement.update
(package:flutter/src/widgets/framework.dart:4863:5)
#311    Element.updateChild
(package:flutter/src/widgets/framework.dart:3405:15)
#312    ComponentElement.performRebuild
(package:flutter/src/widgets/framework.dart:4683:16)
#313    Element.rebuild
(package:flutter/src/widgets/framework.dart:4348:5)
#314    ProxyElement.update
(package:flutter/src/widgets/framework.dart:5011:5)
#315    Element.updateChild
(package:flutter/src/widgets/framework.dart:3405:15)
#316    ComponentElement.performRebuild
(package:flutter/src/widgets/framework.dart:4683:16)
#317    Element.rebuild
(package:flutter/src/widgets/framework.dart:4348:5)
#318    ProxyElement.update
(package:flutter/src/widgets/framework.dart:5011:5)
#319    _InheritedNotifierElement.update
(package:flutter/src/widgets/inherited_notifier.dart:181:11)
#320    Element.updateChild
(package:flutter/src/widgets/framework.dart:3405:15)
#321    SingleChildRenderObjectElement.update
(package:flutter/src/widgets/framework.dart:6193:14)
#322    Element.updateChild
(package:flutter/src/widgets/framework.dart:3405:15)
#323    ComponentElement.performRebuild
(package:flutter/src/widgets/framework.dart:4683:16)
#324    StatefulElement.performRebuild
(package:flutter/src/widgets/framework.dart:4831:11)
#325    Element.rebuild
(package:flutter/src/widgets/framework.dart:4348:5)
#326    StatefulElement.update
(package:flutter/src/widgets/framework.dart:4863:5)
#327    Element.updateChild
(package:flutter/src/widgets/framework.dart:3405:15)
#328    SingleChildRenderObjectElement.update
(package:flutter/src/widgets/framework.dart:6193:14)
#329    Element.updateChild
(package:flutter/src/widgets/framework.dart:3405:15)
#330    SingleChildRenderObjectElement.update
(package:flutter/src/widgets/framework.dart:6193:14)
#331    Element.updateChild
(package:flutter/src/widgets/framework.dart:3405:15)
#332    ComponentElement.performRebuild
(package:flutter/src/widgets/framework.dart:4683:16)
#333    Element.rebuild
(package:flutter/src/widgets/framework.dart:4348:5)
#334    ProxyElement.update
(package:flutter/src/widgets/framework.dart:5011:5)
#335    Element.updateChild
(package:flutter/src/widgets/framework.dart:3405:15)
#336    ComponentElement.performRebuild
(package:flutter/src/widgets/framework.dart:4683:16)
#337    StatefulElement.performRebuild
(package:flutter/src/widgets/framework.dart:4831:11)
#338    Element.rebuild
(package:flutter/src/widgets/framework.dart:4348:5)
#339    BuildOwner.buildScope
(package:flutter/src/widgets/framework.dart:2620:33)
#340    WidgetsBinding.drawFrame
(package:flutter/src/widgets/binding.dart:878:21)
#341    RendererBinding._handlePersistentFrameCallback
(package:flutter/src/rendering/binding.dart:330:5)
#342    SchedulerBinding._invokeFrameCallback
(package:flutter/src/scheduler/binding.dart:1143:15)
#343    SchedulerBinding.handleDrawFrame
(package:flutter/src/scheduler/binding.dart:1080:9)
#344    SchedulerBinding._handleDrawFrame
(package:flutter/src/scheduler/binding.dart:996:5)
#348    _invoke (dart:ui/hooks.dart:163:10)
#349    PlatformDispatcher._drawFrame
(dart:ui/platform_dispatcher.dart:259:5)
#350    _drawFrame (dart:ui/hooks.dart:126:31)
(elided 3 frames from dart:async)

════════════════════════════════════════════════════════════
════════════════════════════════════════

To Reproduce:

-Download and setup flutter_stripe example app
-Run on macOS
-Navigate to either card payment using web hooks screen, card payment without web hooks screen, setup future payment screen, or card themes screen

Expected Behavior:

Screen shows all card input fields

**Comment by jonasbark** [comment]
No, it's not compatible with macOS
