### ISSUE TITLE
Card form request does not await for result

### ISSUE THREAD

**Issue by vmoone** [jonasbark/flutter_stripe_payment#62]
Hi there,
I just updated the library and when this method below is called
```
StripePayment.paymentRequestWithCardForm(
                          CardFormPaymentRequest())
                      .catchError((e) {
                    print('ERROR ${e.toString()}');
                  }).then((paymentMethod) {
                    print(paymentMethod.toJson());
                  });
```
It opens the card form dialog and it throws this exception:
```
I/flutter (17817): ERROR PlatformException(NullPointerException, Attempt to invoke virtual method 'void android.app.Dialog.setOnCancelListener(android.content.DialogInterface$OnCancelListener)' on a null object reference, null)
E/flutter (17817): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: NoSuchMethodError: The getter 'card' was called on null.
E/flutter (17817): Receiver: null
E/flutter (17817): Tried calling: card
```
I checked and see that the future does not await for the result and so it goes immediately on.

If I fill the card form and click on SAVE, the app crashes :

```
D/AndroidRuntime(21951): Shutting down VM
E/AndroidRuntime(21951): FATAL EXCEPTION: main
E/AndroidRuntime(21951): java.lang.IllegalStateException: Reply already submitted
E/AndroidRuntime(21951): 	at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:151)
E/AndroidRuntime(21951): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:225)
E/AndroidRuntime(21951): 	at com.facebook.react.bridge.Promise.resolve(Promise.java:17)
E/AndroidRuntime(21951): 	at com.gettipsi.stripe.StripeModule$5.invoke(StripeModule.java:201)
E/AndroidRuntime(21951): 	at com.gettipsi.stripe.StripeModule$5.invoke(StripeModule.java:198)
E/AndroidRuntime(21951): 	at de.jonasbark.stripepayment.StripeDialog$getToken$$inlined$let$lambda$1.onSuccess(StripeDialog.kt:85)
E/AndroidRuntime(21951): 	at de.jonasbark.stripepayment.StripeDialog$getToken$$inlined$let$lambda$1.onSuccess(StripeDialog.kt:80)
E/AndroidRuntime(21951): 	at com.stripe.android.ApiOperation.onPostExecute(ApiOperation.java:32)
E/AndroidRuntime(21951): 	at com.stripe.android.ApiOperation.onPostExecute(ApiOperation.java:11)
E/AndroidRuntime(21951): 	at android.os.AsyncTask.finish(AsyncTask.java:695)
E/AndroidRuntime(21951): 	at android.os.AsyncTask.access$600(AsyncTask.java:180)
E/AndroidRuntime(21951): 	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:712)
E/AndroidRuntime(21951): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(21951): 	at android.os.Looper.loop(Looper.java:193)
E/AndroidRuntime(21951): 	at android.app.ActivityThread.main(ActivityThread.java:6863)
E/AndroidRuntime(21951): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(21951): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
E/AndroidRuntime(21951): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
W/OPDiagnose(21951): getService:OPDiagnoseService NULL
D/OSTracker(21951): OS Event: crash
I/Process (21951): Sending signal. PID: 21951 SIG: 9
```

Thank you for your help.

**Comment by jonasbark** [comment]
Thanks for letting me know! I just uploaded 1.0.2 with a fix

**Comment by vmoone** [comment]
Alright everything is working fine. Thank you for being so fast.
Unfortunately, it is not very clear to me how to get a token to proceed with payments. I read the original docs, but I found no clues.
Once I got the paymentMethod, what function should I call to get the token and save it?
I tried with `.createTokenWithCard(params)` but it needs the card number, that is not returned by the paymentMethod.
Sorry for going to another issue, thank you again.

**Comment by jonasbark** [comment]
There's no way to "proceed" with payments from this plugin if you don't use native payments. This plugin is only meant to fetch the data, e.g. PaymentIntent etc. so that you can forward it to a server which handles the actual payments.
Head to https://github.com/tipsi/tipsi-stripe for additional information.

**Comment by vmoone** [comment]
Ok, I was asking just because there are various tutorial using this library showing different way to get a token. That is the only thing I need. It was done by using `StripeSource.addSource()` in the past, but as it is no longer available, I was wondering what is the best way to get the token.

**Comment by jonasbark** [comment]
addSource returned the token directly - now you should use createTokenWithCard that results in a Token object that contains that exact token.

**Comment by vmoone** [comment]
Perfect, that is what I meant to do:
```
StripePayment.paymentRequestWithCardForm(
                      CardFormPaymentRequest())
                      .catchError((e) {
                    print('ERROR ${e.toString()}');
                  }).then((paymentMethod) {
                    StripePayment.createTokenWithCard(paymentMethod.card);
                  }); 
```
It throws this exception:
```

W/System.err(28438): com.stripe.android.exception.InvalidRequestException: Missing required param: card[number].; request-id: req_E4sxBUnyyI8cRQ
W/System.err(28438): 	at com.stripe.android.StripeApiRepository.handleAPIError(StripeApiRepository.kt:784)
W/System.err(28438): 	at com.stripe.android.StripeApiRepository.makeApiRequest(StripeApiRepository.kt:828)
W/System.err(28438): 	at com.stripe.android.StripeApiRepository.requestToken(StripeApiRepository.kt:872)
W/System.err(28438): 	at com.stripe.android.StripeApiRepository.createToken(StripeApiRepository.kt:340)
W/System.err(28438): 	at com.stripe.android.Stripe$CreateTokenTask.getResult(Stripe.java:1447)
W/System.err(28438): 	at com.stripe.android.Stripe$CreateTokenTask.getResult(Stripe.java:1425)
W/System.err(28438): 	at com.stripe.android.ApiOperation.doInBackground(ApiOperation.java:22)
W/System.err(28438): 	at com.stripe.android.ApiOperation.doInBackground(ApiOperation.java:11)
W/System.err(28438): 	at android.os.AsyncTask$2.call(AsyncTask.java:333)
W/System.err(28438): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
W/System.err(28438): 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
W/System.err(28438): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
W/System.err(28438): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
W/System.err(28438): 	at java.lang.Thread.run(Thread.java:764)
E/flutter (28438): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: PlatformException(invalidRequest, Missing required param: card[number]., null)

```

**Comment by jonasbark** [comment]
Look... you already have the token in the paymentMethod - why do you want to create that again? Just use paymentMethod.id and be done with it.

Please also make use of the debugger and you'll see that paymentMethod.card does not include data which is how it's supposed to work.

**Comment by jamesdixon** [comment]
@vmoone yes, thanks. appreciate the library but the api is not very clear IMo

**Comment by hkmsadek** [comment]
paymentMethod.id  is not token and it doesn't work for one time payment. Any clue to get the token?

**Comment by TheGhostDevlopper** [comment]
but if I want to have token.card.fingerprint in my backend, so for that I need the token card who are null in flutter, and I also can't get it with paymentmethods.card.token in my backend.

**Comment by zeromaro** [comment]
I've quick question to this topic - I've used `StripePayment.paymentRequestWithCardForm()` - after entering any card information - it returns me token id all the time. Even though credit card information is wrong  (https://stripe.com/docs/testing) (4000000000000127 - incorrect cvv, I should not be able to proceed further).

I was wondering where error handling is being made? Because now it seems it goes through all the time
