### ISSUE TITLE
Flutter Stripe payment integration not working

### ISSUE THREAD

**Issue by rahulmishra1991** [jonasbark/flutter_stripe_payment#8]
I am trying to implement stripe payment plugin for flutter and add the plugin in pubspec.yaml same as flutter stripe payment example but it gives me below error... I am using in the new fresh application.

Performing hot restart...
Syncing files to device Android SDK built for x86...
Restarted application in 2,713ms.
E/flutter ( 4683): [ERROR:flutter/shell/common/shell.cc(181)] Dart Error: Unhandled exception:
E/flutter ( 4683): MissingPluginException(No implementation found for method setPublishableKey on channel stripe_payment)
E/flutter ( 4683): #0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:278:7)
E/flutter ( 4683): <asynchronous suspension>
E/flutter ( 4683): #1      StripeSource.setPublishableKey (package:stripe_payment/stripe_payment.dart:21:14)
E/flutter ( 4683): #2      _MyAppState.initState (file:///E:/workstation/stripe_app/lib/main.dart:20:18)
E/flutter ( 4683): #3      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3763:58)
E/flutter ( 4683): #4      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3629:5)
E/flutter ( 4683): #5      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
E/flutter ( 4683): #6      Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
E/flutter ( 4683): #7      RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:881:16)
E/flutter ( 4683): #8      RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:852:5)
E/flutter ( 4683): #9      RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:798:17)
E/flutter ( 4683): #10     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2235:19)
E/flutter ( 4683): #11     RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:797:13)
E/flutter ( 4683): #12     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:689:7)
E/flutter ( 4683): #13     runApp (package:flutter/src/widgets/binding.dart:728:7)
E/flutter ( 4683): #14     main (file:///E:/workstation/stripe_app/lib/main.dart:6:3)
E/flutter ( 4683): #15     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:289:19)
E/flutter ( 4683): #16     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
E/flutter ( 4683): [ERROR:flutter/shell/common/shell.cc(181)] Dart Error: Unhandled exception:
E/flutter ( 4683): MissingPluginException(No implementation found for method addSource on channel stripe_payment)
E/flutter ( 4683): #0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:278:7)
E/flutter ( 4683): <asynchronous suspension>
E/flutter ( 4683): #1      StripeSource.addSource (package:stripe_payment/stripe_payment.dart:12:41)
E/flutter ( 4683): <asynchronous suspension>
E/flutter ( 4683): #2      _MyAppState.initState (file:///E:/workstation/stripe_app/lib/main.dart:21:18)
E/flutter ( 4683): #3      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3763:58)
E/flutter ( 4683): #4      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3629:5)
E/flutter ( 4683): #5      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
E/flutter ( 4683): #6      Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
E/flutter ( 4683): #7      RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:881:16)
E/flutter ( 4683): #8      RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:852:5)
E/flutter ( 4683): #9      RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:798:17)
E/flutter ( 4683): #10     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2235:19)
E/flutter ( 4683): #11     RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:797:13)
E/flutter ( 4683): #12     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:689:7)
E/flutter ( 4683): #13     runApp (package:flutter/src/widgets/binding.dart:728:7)
E/flutter ( 4683): #14     main (file:///E:/workstation/stripe_app/lib/main.dart:6:3)
E/flutter ( 4683): #15     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:289:19)
E/flutter ( 4683): #16     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)

**Comment by jonasbark** [comment]
Looks more like a flutter issue to me. Try a clean build?

**Comment by rahulmishra1991** [comment]
how do i send clean build are you asking for flutter doctor?

**Comment by rahulmishra1991** [comment]
C:\Users\admin>flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, v0.7.3, on Microsoft Windows [Version 10.0.17134.228], locale en-IN)
[√] Android toolchain - develop for Android devices (Android SDK 28.0.1)
[√] Android Studio (version 3.1)
[√] Connected devices (1 available)

• No issues found!

**Comment by rahulmishra1991** [comment]
https://stackoverflow.com/questions/52380240/flutter-package-get-not-working-for-stripe-plugins-only

**Comment by rahulmishra1991** [comment]
Only stripe plugins not working everything working fine i don't know why? I tried many time and created new projects for flutter stripe only and same issue happening can you please help me into this?

I shared detailed message above.

**Comment by andreabtis** [comment]
open only the Android project in a new window on AS:

1. Add in the MainActivity the FlutterFragmentActivity():   like this:

class MainActivity(): **FlutterFragmentActivity()** {
  override fun onCreate(savedInstanceState: Bundle?) {
    super.onCreate(savedInstanceState)
    GeneratedPluginRegistrant.registerWith(this)
  }
}

2. Customize imports
3. Upgrade the kotlin version in build.gradle file of your app: 
ext.kotlin_version = '1.2.71'

and thats it! 👍

**Comment by BroPet89** [comment]
Changing FlutterActivity to FlutterFragmentActivity gives me the following error:

**Comment by jonasbark** [comment]
Closing this as it's not a plugin issue - let me know if you think otherwise.

**Comment by RizzWann** [comment]
e: [C:\flutter\.pub-cache\hosted\pub.dartlang.org\stripe_android-2.4.0\android\src\main\kotlin\com\flutter\stripe\StripeAubecsDebitPlatformViewFactory.kt](): (13, 1): Class 'StripeAubecsDebitPlatformViewFactory' is not abstract and does not implement abstract base class member public abstract fun create(p0: Context?, p1: Int, p2: Any?): PlatformView defined in io.flutter.plugin.platform.PlatformViewFactory
e: [C:\flutter\.pub-cache\hosted\pub.dartlang.org\stripe_android-2.4.0\android\src\main\kotlin\com\flutter\stripe\StripeAubecsDebitPlatformViewFactory.kt](): (19, 5): 'create' overrides nothing
e: [C:\flutter\.pub-cache\hosted\pub.dartlang.org\stripe_android-2.4.0\android\src\main\kotlin\com\flutter\stripe\StripeSdkCardFormPlatformViewFactory.kt](): (13, 1): Class 'StripeSdkCardFormPlatformViewFactory' is not abstract and does not implement abstract base class member public abstract fun create(p0: Context?, p1: Int, p2: Any?): PlatformView defined in io.flutter.plugin.platform.PlatformViewFactory

**Comment by RizzWann** [comment]
e: [C:\flutter\.pub-cache\hosted\pub.dartlang.org\stripe_android-2.4.0\android\src\main\kotlin\com\flutter\stripe\StripeAubecsDebitPlatformViewFactory.kt](): (13, 1): Class 'StripeAubecsDebitPlatformViewFactory' is not abstract and does not implement abstract base class member public abstract fun create(p0: Context?, p1: Int, p2: Any?): PlatformView defined in io.flutter.plugin.platform.PlatformViewFactory
e: [C:\flutter\.pub-cache\hosted\pub.dartlang.org\stripe_android-2.4.0\android\src\main\kotlin\com\flutter\stripe\StripeAubecsDebitPlatformViewFactory.kt](): (19, 5): 'create' overrides nothing
e: [C:\flutter\.pub-cache\hosted\pub.dartlang.org\stripe_android-2.4.0\android\src\main\kotlin\com\flutter\stripe\StripeSdkCardFormPlatformViewFactory.kt](): (13, 1): Class 'StripeSdkCardFormPlatformViewFactory' is not abstract and does not implement abstract base class member public abstract fun create(p0: Context?, p1: Int, p2: Any?): PlatformView defined in io.flutter.plugin.platform.PlatformViewFactory

ANY FIX?

**Comment by kamami** [comment]
Same issue! Using `flutter_stripe 2.5.0` on the latest `flutter stable` version...
